import type {Certificate} from '@/learner/model';
import type {Course} from '@/content/catalog';
function lines(ctx:CanvasRenderingContext2D,text:string,width:number){const out:string[]=[];for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(ctx.measureText(word).width>width){if(line){out.push(line);line='';}for(const char of word){if(ctx.measureText(line+char).width>width){out.push(line);line=char;}else line+=char;}continue;}const candidate=line?line+' '+word:word;if(ctx.measureText(candidate).width>width&&line){out.push(line);line=word;}else line=candidate;}if(line)out.push(line);}return out;}
export async function downloadCertificate(cert:Certificate,course:Course){
  await Promise.all([document.fonts.load('600 72px Barlow'),document.fonts.load('500 58px DM'),document.fonts.load('400 28px DM')]);await document.fonts.ready;
  const canvas=document.createElement('canvas');canvas.width=1800;canvas.height=1200;const ctx=canvas.getContext('2d');if(!ctx)throw Error('Image export is unavailable. Use Print certificate instead.');
  ctx.fillStyle='#f8f7f2';ctx.fillRect(0,0,1800,1200);ctx.strokeStyle='#c7c9be';ctx.lineWidth=3;ctx.strokeRect(42,42,1716,1116);ctx.strokeRect(58,58,1684,1084);
  ctx.strokeStyle='#151719';ctx.lineWidth=3;const x=682,y=122;ctx.beginPath();ctx.moveTo(x,y+18);ctx.lineTo(x,y);ctx.lineTo(x+18,y);ctx.moveTo(x+34,y);ctx.lineTo(x+52,y);ctx.lineTo(x+52,y+18);ctx.moveTo(x+52,y+34);ctx.lineTo(x+52,y+52);ctx.lineTo(x+34,y+52);ctx.moveTo(x+18,y+52);ctx.lineTo(x,y+52);ctx.lineTo(x,y+34);ctx.stroke();ctx.fillStyle='#151719';ctx.fillRect(x+20,y+20,12,12);
  ctx.textAlign='left';ctx.font='600 38px Barlow';ctx.fillText('FRAME ACADEMY',759,158);ctx.fillStyle='#7a842d';ctx.fillRect(856,240,88,6);ctx.textAlign='center';ctx.fillStyle='#151719';ctx.font='600 83px Barlow';ctx.fillText('A STUDY, COMPLETED.',900,370);ctx.font='400 26px DM';ctx.fillText('This demo completion certificate is presented to',900,435);
  let size=58;let nameLines:string[]=[];do{ctx.font=`500 ${size}px DM`;nameLines=lines(ctx,cert.name,1460);if(nameLines.length<=3)break;size-=2;}while(size>28);const nameStart=520;nameLines.forEach((line,i)=>ctx.fillText(line,900,nameStart+i*(size+12)));const nameEnd=nameStart+(nameLines.length-1)*(size+12);
  ctx.font='400 26px DM';ctx.fillText('for completing the three lessons and final quiz in',900,nameEnd+70);ctx.font='600 65px Barlow';const titleLines=lines(ctx,course.title,1400);titleLines.forEach((line,i)=>ctx.fillText(line,900,nameEnd+155+i*70));
  const date=new Date(cert.at).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'});ctx.font='400 23px DM';ctx.fillStyle='#4f554d';ctx.fillText(`Issued ${date}`,900,971);ctx.font='400 20px DM';ctx.fillText(`Local reference: ${cert.ref}`,900,1011);ctx.fillStyle='#151719';ctx.font='500 24px DM';ctx.fillText('Demo completion certificate — portfolio project; not accredited',900,1090);
  const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Image export failed. Try Print certificate.')),'image/png'));const url=URL.createObjectURL(blob),a=document.createElement('a');a.download=`frame-academy-${course.slug}-demo-certificate.png`;a.href=url;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
