'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {getCourse} from '@/content/catalog';
import {useLearner} from '@/learner/provider';
import {courseComplete,continueUrl} from '@/learner/model';
import {EmptyState,Icon,Mark} from '@/components/ui';
export function Certificates(){const s=useLearner();if(!s.ready)return <p className="loading-state">Loading your certificates…</p>;const certs=Object.values(s.data.certificates);return certs.length?<div className="certificate-grid">{certs.map(cert=>{const c=getCourse(cert.courseId)!;return <Link className="certificate-card" key={c.id} href={`/certificate/?course=${c.slug}`}><Mark/><div><h2>{c.title}</h2><p>{cert.name} · {new Date(cert.at).toLocaleDateString('en-US')}<br/>Demo completion certificate</p></div><Icon name="arrow"/></Link>;})}</div>:<EmptyState title="Make the work. Mark the moment." text="Complete all three lessons and pass a course quiz with at least 4/5 to earn a clearly labeled demo certificate." href="/my-learning/" action="Go to My Learning"/>;}
export function CertificatePage(){const s=useLearner(),params=useSearchParams();const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);const c=getCourse(params.get('course')||'');if(!s.ready)return <div className="wrap loading-state">Loading the local certificate…</div>;if(!c)return <div className="wrap"><EmptyState title="Choose a certificate." text="This link does not identify a known course. Your earned records are listed under Certificates." href="/certificates/" action="Your certificates"/></div>;const cert=s.data.certificates[c.id];if(!cert||!courseComplete(s.data,c))return <div className="wrap"><EmptyState title="A little more work to make." text={`A ${c.title} demo certificate is available after all three lessons are complete and the quiz is passed. This browser does not have an earned record yet.`} href={s.data.enrollments[c.id]?continueUrl(s.data,c):`/courses/${c.slug}/`} action={s.data.enrollments[c.id]?'Continue learning':'View course'}/></div>;async function download(){if(!cert||!c)return;setBusy(true);setMessage('Preparing your certificate…');try{const {downloadCertificate}=await import('./export');await downloadCertificate(cert,c);setMessage('Certificate image prepared. Check your browser’s downloads.');}catch(e){setMessage(e instanceof Error?e.message:'Export failed. Use Print certificate.');}finally{setBusy(false);}}return <div className="certificate-page"><Link className="back-link" href="/certificates/">Your certificates</Link><article className="certificate-paper"><div className="certificate-brand"><Mark/>FRAME ACADEMY</div><div className="certificate-rule"/><h1>A STUDY, COMPLETED.</h1><p>This demo completion certificate is presented to</p><div className="certificate-name">{cert.name}</div><p>for completing the three lessons and final quiz in</p><h2>{c.title}</h2><div className="certificate-details">Issued {new Date(cert.at).toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}<br/>Local reference: {cert.ref}</div><p className="certificate-disclaimer">Demo completion certificate — portfolio project; not accredited</p></article><div className="certificate-actions"><button className="button primary" disabled={busy} onClick={download}><Icon name="download"/>{busy?'Preparing image…':'Download certificate PNG'}</button><button className="button secondary" onClick={()=>window.print()}>Print certificate</button><span className="status" role="status">{message}</span></div><div className="notice">Portfolio demo. Learning data is stored in this browser. No payment is taken.<br/>This certificate is not proof of accredited training, verified identity or employment eligibility. Its name is an issuance snapshot. The local page link will not reproduce your achievement on another device; keep the downloaded file.</div></div>;}
