'use client';
import Link from 'next/link';
import {useState} from 'react';
import {type Course,lessonUrl} from '@/content/catalog';
import {useLearner} from '@/learner/provider';
import {courseComplete,continueUrl,quizPassed,submitQuiz} from '@/learner/model';
import {EmptyState,Icon} from '@/components/ui';
export function CourseQuiz({course:c}:{course:Course}){const s=useLearner();if(!s.ready)return <div className="wrap loading-state">Loading your quiz…</div>;if(!s.data.enrollments[c.id])return <div className="wrap"><EmptyState title="Put your eye to the test." text="Enroll in the demo to save quiz attempts and work toward a completion certificate. No payment is taken." href={`/enroll/?course=${c.slug}`} action="Enroll in demo"/></div>;return <QuizForm course={c}/>;}
function QuizForm({course:c}:{course:Course}){const s=useLearner();const existing=s.data.quizzes[c.id];const [answers,setAnswers]=useState<number[]>(existing?.draft.length===5?existing.draft:Array(5).fill(-1)),[message,setMessage]=useState(''),[attemptId,setAttemptId]=useState(()=>crypto.randomUUID()),[submitted,setSubmitted]=useState(false);const result=existing?.attempts.find(a=>a.id===attemptId);const best=Math.max(0,...(existing?.attempts.map(a=>a.score)||[]));function answer(i:number,v:number){const next=answers.map((n,j)=>i===j?v:n);setAnswers(next);const ok=s.mutate(d=>{d.quizzes[c.id]={...(d.quizzes[c.id]||{attempts:[]}),draft:next};});setMessage(ok?s.mode==='temporary'?'Draft updated for this temporary session.':'Draft saved.':'Draft was not saved. Check the storage notice.');}function submit(){if(answers.some(a=>a<0)){setMessage('Answer all five questions before submitting.');document.getElementById(`question-${answers.findIndex(a=>a<0)}`)?.focus();return;}const ok=s.mutate(d=>{submitQuiz(d,c,answers,new Date().toISOString(),attemptId);});if(ok)setSubmitted(true);setMessage(ok?'Attempt recorded. Review the explanations below.':'Attempt was not saved. Check the storage notice.');}return <div className="quiz-layout"><Link className="back-link" href={`/courses/${c.slug}/`}>{c.title} / Final quiz</Link><h1>What did you see?</h1><p>Five questions about the choices behind the frame. Answer at least four correctly to pass. You can retry and learn from every explanation.</p><div className="notice">{quizPassed(s.data,c.id)?`You have passed this quiz. Best score: ${best}/5. A lower retry will preserve your achievement.`:'Your answers save as a draft. Finish all three lessons and pass this quiz to earn the demo certificate.'}</div>{submitted&&result&&<div className="quiz-result" role="status"><h2>{result.score>=4?'A sharper eye.':'Look again. Try again.'} {result.score}/5</h2><p>{result.score>=4?'Quiz passed. Review the explanations to connect the answers to your work.':'Four correct answers are needed. Read the explanations, then make another attempt.'}</p>{courseComplete(s.data,c)?<Link className="button primary" href={`/certificate/?course=${c.slug}`}>View your demo certificate<Icon name="arrow"/></Link>:<Link className="button secondary" href={continueUrl(s.data,c)}>Return to your remaining work<Icon name="arrow"/></Link>}</div>}
  {c.quiz.map((q,i)=><fieldset className="quiz-question" key={q.prompt} disabled={submitted}><legend id={`question-${i}`} tabIndex={-1}>{i+1}. {q.prompt}</legend>{q.options.map((option,j)=><label key={option}><input type="radio" name={`q${i}`} value={j} checked={answers[i]===j} onChange={()=>answer(i,j)}/><span>{option}</span></label>)}{submitted&&result&&<div className="quiz-feedback"><h3 className={result.answers[i]===q.correct?'success':'error'}>{result.answers[i]===q.correct?'Correct':'Review this answer'} · {q.options[q.correct]}</h3><p>{q.explanation}</p></div>}</fieldset>)}<p className="status" role="status">{message}</p><div className="form-actions">{submitted?<button className="button primary" onClick={()=>{setSubmitted(false);setAttemptId(crypto.randomUUID());setAnswers(Array(5).fill(-1));s.mutate(d=>{d.quizzes[c.id].draft=Array(5).fill(-1);});setMessage('A fresh attempt is ready.');window.scrollTo({top:0,behavior:'instant'});}}>Try again<Icon name="arrow"/></button>:<button className="button primary" onClick={submit}>Submit answers<Icon name="check"/></button>}<Link className="text-link" href={lessonUrl(c,c.lessons[0])}>Review the lessons</Link></div>{!!existing?.attempts.length&&<details className="attempt-list"><summary>Attempt history · Best {best}/5 · {existing.attempts.length} attempt{existing.attempts.length===1?'':'s'}</summary><ul>{[...existing.attempts].reverse().map((a,i)=><li key={a.id}>Attempt {existing.attempts.length-i}: {a.score}/5 · {a.score>=4?'Passed':'Try again'} · {new Date(a.at).toLocaleString('en-US')}</li>)}</ul></details>}</div>;}
