'use client';
import {useCallback,useEffect,useRef,useState,type RefObject} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {type Course,type Lesson,formatTime,lessonUrl,readingMinutes} from '@/content/catalog';
import {useLearner} from '@/learner/provider';
import {completedLessons,continueUrl,markLesson,progressLabel,type Note} from '@/learner/model';
import {Icon} from '@/components/ui';
export function LessonWorkspace({course:c,lesson:l}:{course:Course;lesson:Lesson}) {
  const s=useLearner(),router=useRouter();const video=useRef<HTMLVideoElement>(null);const [tab,setTab]=useState('Notes');const [feedback,setFeedback]=useState('');const tabRefs=useRef<(HTMLButtonElement|null)[]>([]);
  const enrolled=!!s.data.enrollments[c.id],complete=!!s.data.progress[l.id]?.completedAt,index=c.lessons.findIndex(x=>x.id===l.id);const {ready,mutate}=s;
  useEffect(()=>{if(ready&&enrolled)mutate(d=>{d.lastVisit={courseId:c.id,lessonId:l.id,at:new Date().toISOString()};});},[ready,enrolled,c.id,l.id,mutate]);
  function finish(){const ok=s.mutate(d=>{markLesson(d,c,l.id,new Date().toISOString());});setFeedback(ok?s.mode==='temporary'?'Marked complete for this temporary session.':'Lesson marked complete.': 'Completion was not saved. Check the storage notice and retry.');}
  function seek(time:number){if(video.current && Number.isFinite(video.current.duration)) {video.current.currentTime=Math.max(0,Math.min(time,video.current.duration));video.current.focus();}else setFeedback('Load the video first, then choose the timestamp again.');}
  const gated=s.ready&&!enrolled&&l.kind!=='video';
  return <><div className="learn-topbar"><Link href={`/courses/${c.slug}/`}>{c.title}<Icon name="chevron" size={16}/><span>Learning studio</span></Link><div className="progress-summary"><span>{enrolled?progressLabel(s.data,c):'Free preview · Get a feel for the course'}</span><div className="progress-track"><span style={{width:`${completedLessons(s.data,c)/3*100}%`}}/></div></div></div><div className="learning-layout"><section className="lesson-main"><div className="mobile-curriculum field"><label htmlFor="curriculum-select">Course curriculum</label><select id="curriculum-select" value={l.slug} onChange={e=>router.push(lessonUrl(c,e.target.value))}>{c.lessons.map((item,n)=><option value={item.slug} key={item.id}>{n+1}. {item.title}{s.data.progress[item.id]?.completedAt?' ✓':''}</option>)}<option value="quiz">Final quiz</option></select></div><div className="lesson-identity"><div><span>LESSON {String(index+1).padStart(2,'0')} OF 03 · {l.kind==='video'?'VISUAL LESSON · 1:00':l.kind==='reading'?`ILLUSTRATED READING · ~${readingMinutes(c)} MIN`:'GUIDED PRACTICE'}</span><h1>{l.title}</h1></div>{complete&&<span className="success"><Icon name="check"/>Complete</span>}</div>
  {gated?<div className="empty-state"><h2>Make this your next study.</h2><p>Enroll in the demo to save your progress, make notes and work through the practice. No payment or password is needed.</p><Link className="button primary" href={`/enroll/?course=${c.slug}`}>Enroll in demo<Icon name="arrow"/></Link></div>:<>
  {l.kind==='video'?<TeachingVideo course={c} lesson={l} videoRef={video} onMessage={setFeedback}/>:l.kind==='reading'?<Reading course={c}/>:s.ready?<Practice course={c} lesson={l} key={`${l.id}-${s.data.enrollments[c.id]?.ref||'preview'}`}/>:<p className="loading-state">Loading your practice workspace…</p>}
  {l.kind!=='practice'&&<div className="lesson-description"><p>{l.kind==='video'?'A silent visual demonstration. Follow the on-screen study, or use the timestamped transcript below.':'Compare the example with something you can see around you. Mark this reading complete when you are ready to make your study.'}</p>{enrolled?<button className="button secondary" disabled={complete} onClick={finish}>{complete?<><Icon name="check"/>Lesson complete</>:'Mark complete'}</button>:<Link className="button primary" href={`/enroll/?course=${c.slug}`}>Enroll in demo<Icon name="arrow"/></Link>}</div>}
  <p className={`status ${feedback.includes('not saved')?'error':''}`} role="status">{feedback}</p>
  <div className="workspace-tabs" role="tablist" aria-label="Lesson workspace">{['Notes','Transcript','Resources'].map((t,i)=><button role="tab" id={`tab-${t}`} aria-controls={`panel-${t}`} aria-selected={tab===t} tabIndex={tab===t?0:-1} ref={el=>{tabRefs.current[i]=el;}} key={t} onClick={()=>setTab(t)} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;setTab(['Notes','Transcript','Resources'][next]);tabRefs.current[next]?.focus();}}}>{t}</button>)}</div>
  <div className="workspace-tab-panel" role="tabpanel" id={`panel-${tab}`} aria-labelledby={`tab-${tab}`} tabIndex={0}>{tab==='Notes'?<LessonNotes course={c} lesson={l} time={()=>video.current?.currentTime||0} seek={seek}/>:tab==='Transcript'?l.kind==='video'?<>{c.chapters.map(ch=><div className="transcript-row" key={ch.time}><button onClick={()=>seek(ch.time)} aria-label={`Seek to ${formatTime(ch.time)}: ${ch.title}`}>{formatTime(ch.time)}</button><div><h3>{ch.title}</h3><p>{ch.text}</p></div></div>)}</>:<p>This lesson is presented as text above. The course’s video transcript is available in Resources.</p>:<><Resource href={`/resources/${c.id}-worksheet.md`} title="Your field worksheet" description="Original practice brief, equipment checklist and reflection prompts · Markdown"/><Resource href={`/resources/${c.id}-transcript.txt`} title="Visual lesson transcript" description="Complete text equivalent of the 60-second teaching clip · Plain text"/><Resource href={`/media/${c.id}.vtt`} title="Timed explanatory text" description="WebVTT text matching the visual lesson · 6 timed sections"/></>}</div>
  </>}
  <nav className="lesson-nav" aria-label="Lesson navigation">{index>0?<Link className="text-link" href={lessonUrl(c,c.lessons[index-1])}>Previous lesson</Link>:<Link className="text-link" href={`/courses/${c.slug}/`}>Course overview</Link>}<Link className="button secondary" href={lessonUrl(c,index===2?'quiz':c.lessons[index+1])}>{index===2?'Go to final quiz':'Next lesson'}<Icon name="arrow"/></Link></nav></section><aside className="curriculum-rail"><h2>Your course</h2>{c.lessons.map((item,n)=><Link className={`rail-link ${s.data.progress[item.id]?.completedAt?'complete':''}`} aria-current={l.id===item.id?'page':undefined} href={lessonUrl(c,item)} key={item.id}><span>{s.data.progress[item.id]?.completedAt?<Icon name="check" size={18}/>:String(n+1).padStart(2,'0')}</span><span>{item.title}<small>{item.kind==='video'?'Visual lesson · 1:00':item.kind==='reading'?`Reading · ~${readingMinutes(c)} min`:'Guided practice'}</small></span></Link>)}<Link className="rail-link" href={lessonUrl(c,'quiz')}><Icon name="check" size={18}/><span>Final quiz<small>5 questions · 4 correct to pass</small></span></Link><div className="rail-footer"><p>One technique.<br/>A little practice.<br/>A different way to see.</p><Link className="text-link" href="/my-learning/">My learning<Icon name="arrow" size={17}/></Link></div></aside></div></>;
}
function applyCaptions(player:HTMLVideoElement,enabled:boolean){for(const track of player.textTracks)track.mode=enabled?'showing':'hidden';}
function TeachingVideo({course:c,lesson:l,videoRef,onMessage}:{course:Course;lesson:Lesson;videoRef:RefObject<HTMLVideoElement|null>;onMessage:(s:string)=>void}) {
  const s=useLearner();const [state,setState]=useState(''),[speed,setSpeed]=useState(1);const lastWrite=useRef(0),restored=useRef(false);const latest=useRef(s);useEffect(()=>{latest.current=s;},[s]);
  const persist=useCallback((player:HTMLVideoElement)=>{const current=latest.current;if(!current.ready||!current.data.enrollments[c.id]||!Number.isFinite(player.duration))return;const position=Math.min(player.currentTime,player.duration);current.mutate(d=>{d.progress[l.id]={...d.progress[l.id],position,updatedAt:new Date().toISOString()};});},[c.id,l.id]);
  function restore(){const v=videoRef.current;if(!v||!s.ready||!Number.isFinite(v.duration)||restored.current)return;const query=new URLSearchParams(window.location.search),requested=query.has('t')?Number(query.get('t')):s.data.progress[l.id]?.position||0;v.currentTime=Math.min(Math.max(0,Number.isFinite(requested)?requested:0),v.duration);v.playbackRate=s.data.profile.speed;applyCaptions(v,s.data.profile.captions);restored.current=true;}
  useEffect(()=>{const v=videoRef.current;if(!v)return;const flush=()=>persist(v);const visibility=()=>{if(document.visibilityState==='hidden')flush();};document.addEventListener('visibilitychange',visibility);return()=>{flush();document.removeEventListener('visibilitychange',visibility);};},[persist,videoRef]);
  useEffect(()=>{const v=videoRef.current;if(!v||!s.ready||!Number.isFinite(v.duration)||restored.current)return;const query=new URLSearchParams(window.location.search);const requested=query.has('t')?Number(query.get('t')):s.data.progress[l.id]?.position||0;v.currentTime=Math.max(0,Math.min(Number.isFinite(requested)?requested:0,v.duration));v.playbackRate=s.data.profile.speed;applyCaptions(v,s.data.profile.captions);restored.current=true;},[s.ready,s.data.profile.speed,s.data.profile.captions,s.data.progress,l.id,videoRef]);
  useEffect(()=>{const v=videoRef.current;if(!v)return;const error=()=>setState('This video could not load. Retry playback or open the matching transcript in Resources.');v.addEventListener('error',error);if(v.error)queueMicrotask(error);return()=>v.removeEventListener('error',error);},[videoRef]);
  async function play(){try{const v=videoRef.current;if(v?.error)v.load();await v?.play();}catch{setState('Playback was not started. Use the video’s Play control to try again.');}}
  return <><div className="video-shell"><video ref={videoRef} src={`/media/${c.id}.mp4`} controls playsInline preload="metadata" poster={c.image} aria-label={`${c.title}: ${l.title}`} onLoadedMetadata={restore} onRateChange={e=>setSpeed(e.currentTarget.playbackRate)} onTimeUpdate={e=>{if(Date.now()-lastWrite.current>5000){lastWrite.current=Date.now();persist(e.currentTarget);}}} onPause={e=>persist(e.currentTarget)} onWaiting={()=>setState('Buffering the lesson…')} onCanPlay={()=>setState('')} onPlaying={()=>setState('')} onError={()=>setState('This video could not load. Retry playback or open the matching transcript in Resources.')} onEnded={e=>{persist(e.currentTarget);if(s.data.enrollments[c.id]){const ok=s.mutate(d=>{markLesson(d,c,l.id,new Date().toISOString());});onMessage(ok?'Video complete. Your next study is ready.':'Completion was not saved. Check the storage notice.');}}}><track kind="captions" src={`/media/${c.id}.vtt`} srcLang="en" label="English explanatory text"/>Your browser cannot play this video. Use the full transcript below.</video>{state&&<div className="video-state" role="status">{state}<button className="text-button" onClick={play}>Retry playback</button></div>}</div><div className="video-toolbar"><span className="small-text">Silent study · 1:00 · Text available</span><label>Playback speed<select aria-label="Playback speed" value={speed} onChange={e=>{const value=Number(e.target.value);if(videoRef.current)videoRef.current.playbackRate=value;s.mutate(d=>{d.profile.speed=value;});}}>{[.5,.75,1,1.25,1.5,2].map(v=><option value={v} key={v}>{v}×</option>)}</select></label><button className="text-button" onClick={()=>{const v=videoRef.current;if(!v?.textTracks.length)return;const shown=v.textTracks[0].mode!=='showing';v.textTracks[0].mode=shown?'showing':'hidden';s.mutate(d=>{d.profile.captions=shown;});}}>Toggle text captions</button></div></>;
}
function Reading({course:c}:{course:Course}){return <article className="reading-content"><figure><img src={c.image} width="1200" height="800" alt={c.imageAlt}/><figcaption>Look closely: {c.imageAlt} An original generated study for this lesson.</figcaption></figure>{c.reading.map((p,i)=><div key={p.heading}><h2>{p.heading}</h2><p style={{margin:'22px 0',lineHeight:1.85}}>{p.text}</p>{i===1&&<figure><img src={`/diagrams/${c.id}.svg`} alt={`Schematic comparison for ${c.title}: ${c.chapters[4].cue}`} width="1000" height="290" style={{aspectRatio:'1000 / 290',objectFit:'contain'}}/><figcaption>{c.chapters[4].text}</figcaption></figure>}</div>)}</article>;}
function Practice({course:c,lesson:l}:{course:Course;lesson:Lesson}){const s=useLearner(),saved=s.data.progress[l.id];const [checks,setChecks]=useState<boolean[]>(saved?.checks?.length===c.checklist.length?saved.checks:c.checklist.map(()=>false));const [reflection,setReflection]=useState(saved?.reflection||'');const [message,setMessage]=useState('');const complete=!!saved?.completedAt;function save(submit=false){if(submit&&(!checks.every(Boolean)||reflection.trim().length<20)){setMessage('Complete every checklist item and write at least 20 characters in your reflection.');return;}const ok=s.mutate(d=>{d.progress[l.id]={...d.progress[l.id],position:0,checks,reflection:reflection.trim(),updatedAt:new Date().toISOString()};if(submit)markLesson(d,c,l.id,new Date().toISOString());});setMessage(ok?`${submit?'Practice complete':'Draft saved'}${s.mode==='temporary'?' for this temporary session.':' in this browser.'}`:'Your practice was not saved. Check the storage notice and retry.');}return <div className="assignment-brief"><img className="assignment-example" src={c.image} alt={c.imageAlt} width="1200" height="800"/><p className="lead">{c.assignment}</p><div className="notice">Your images and footage stay on your device. Save a written reflection here; no upload is required.</div><div className="checklist">{c.checklist.map((text,i)=><label key={text}><input type="checkbox" checked={checks[i]} disabled={complete} onChange={e=>setChecks(checks.map((v,j)=>j===i?e.target.checked:v))}/><span>{text}</span></label>)}</div><div className="field"><label htmlFor="reflection">{c.reflection}</label><textarea id="reflection" value={reflection} maxLength={5000} readOnly={complete} onChange={e=>setReflection(e.target.value)} placeholder="Describe one choice and the effect you observed…"/><span>At least 20 characters. {reflection.trim().length}/5000</span></div>{complete?<p className="success">Practice complete. Your reflection is saved with this lesson.</p>:<div className="form-actions"><button className="button secondary" onClick={()=>save()}>Save draft</button><button className="button primary" onClick={()=>save(true)}>Submit practice<Icon name="check"/></button></div>}<p className="status" role="status">{message}</p></div>;}
function LessonNotes({course:c,lesson:l,time,seek}:{course:Course;lesson:Lesson;time:()=>number;seek:(t:number)=>void}){const s=useLearner();const [text,setText]=useState(''),[message,setMessage]=useState(''),[includeTime,setIncludeTime]=useState(true);const notes=s.data.notes.filter(n=>n.lessonId===l.id);function create(){if(!text.trim()){setMessage('Write a note before saving.');return;}const at=new Date().toISOString();const ok=s.mutate(d=>{d.notes.push({id:crypto.randomUUID(),courseId:c.id,lessonId:l.id,text:text.trim(),time:l.kind==='video'&&includeTime?Math.min(time(),c.videoSeconds):undefined,createdAt:at,updatedAt:at});});if(ok)setText('');setMessage(ok?s.mode==='temporary'?'Note added to this temporary session.':'Note saved in this browser.':'Note was not saved. Check the storage notice.');}return <><div className="note-composer"><label htmlFor="lesson-note">What did you notice?</label><textarea id="lesson-note" value={text} onChange={e=>setText(e.target.value)} maxLength={5000} placeholder="A useful observation, an idea to try, a decision to remember…"/><div className="form-actions">{l.kind==='video'?<label><input type="checkbox" checked={includeTime} onChange={e=>setIncludeTime(e.target.checked)}/> Include current video timestamp</label>:<span className="small-text">Associated with “{l.title}”</span>}<button className="button small" disabled={!s.ready} onClick={create}>Save note<Icon name="plus" size={17}/></button></div><p className="status" role="status">{message}</p></div>{l.kind==='video'&&<><button className="text-button" onClick={()=>{const current=Math.round(time());const ok=s.mutate(d=>{if(!d.bookmarks.some(b=>b.lessonId===l.id&&b.time===current))d.bookmarks.push({id:crypto.randomUUID(),courseId:c.id,lessonId:l.id,time:current,at:new Date().toISOString()});});setMessage(ok?'Bookmark added.':'Bookmark was not saved.');}}><Icon name="save" size={17}/>Bookmark this moment</button><div className="bookmark-list">{s.data.bookmarks.filter(b=>b.lessonId===l.id).map(b=><div className="bookmark-item" key={b.id}><button onClick={()=>seek(b.time)} aria-label={`Seek bookmark at ${formatTime(b.time)}`}>{formatTime(b.time)}</button><button aria-label={`Delete bookmark at ${formatTime(b.time)}`} onClick={()=>s.mutate(d=>{d.bookmarks=d.bookmarks.filter(x=>x.id!==b.id);})}><Icon name="close" size={14}/></button></div>)}</div></>}{notes.length?notes.map(n=><NoteEditor key={n.id} note={n} seek={seek}/>):<p className="small-text" style={{marginTop:22}}>Your observations will collect here. They’re private to this browser.</p>}</>;}
export function NoteEditor({note:n,seek}:{note:Note;seek?:(time:number)=>void}){const s=useLearner();const [editing,setEditing]=useState(false),[draft,setDraft]=useState(n.text),[message,setMessage]=useState('');function save(){if(!draft.trim()){setMessage('A note cannot be empty.');return;}const ok=s.mutate(d=>{const note=d.notes.find(x=>x.id===n.id);if(note){note.text=draft.trim();note.updatedAt=new Date().toISOString();}});if(ok)setEditing(false);setMessage(ok?'Note updated.':'Edit was not saved.');}return <article className="note-row"><div className="note-context">{n.time!==undefined&&seek?<button className="text-button accent" onClick={()=>seek(n.time!)}>{formatTime(n.time)}<Icon name="play" size={14}/></button>:n.time!==undefined?formatTime(n.time):'Lesson note'} · {new Date(n.updatedAt).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</div>{editing?<><label className="small-text" htmlFor={`edit-${n.id}`}>Edit note</label><textarea className="note-edit" id={`edit-${n.id}`} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={5000}/></>:<p>{n.text}</p>}<div className="note-actions">{editing?<><button className="button small" onClick={save}>Save changes</button><button className="text-button" onClick={()=>{setDraft(n.text);setEditing(false);}}>Cancel</button></>:<button className="text-button" onClick={()=>setEditing(true)}>Edit note</button>}<button className="text-button" onClick={()=>{if(window.confirm('Delete this note from this browser?')){const ok=s.mutate(d=>{d.notes=d.notes.filter(x=>x.id!==n.id);});if(!ok)setMessage('Note could not be deleted.');}}}>Delete</button></div><p className="status" role="status">{message}</p></article>;}
function Resource({href,title,description}:{href:string;title:string;description:string}){return <a href={href} download className="resource-row"><div><h3>{title}</h3><p>{description}</p></div><Icon name="download"/></a>;}
export function ResumeLink({course:c}:{course:Course}){const s=useLearner();return <Link className="button primary" href={continueUrl(s.data,c)}>Continue learning<Icon name="arrow"/></Link>;}
