import type {Metadata} from 'next';
import Link from 'next/link';
import {Navigation} from '@/components/navigation';
import {Wordmark} from '@/components/ui';
import {LearnerProvider,StorageNotice} from '@/learner/provider';
import {pageMeta,siteOrigin} from '@/lib/meta';
import './globals.css';
export const metadata:Metadata={...pageMeta('Learn to see differently.','Photography, film, and visual storytelling. Six compact courses built around observation, practice and making.'),metadataBase:siteOrigin?new URL(siteOrigin):undefined,title:{default:'FRAME ACADEMY — Learn to see differently.',template:'%s | FRAME ACADEMY'},robots:{index:false,follow:true},icons:{icon:'/icon.svg'}};
export default function RootLayout({children}:{children:React.ReactNode}) {return <html lang="en"><body><script type="application/json" id="design-contract" dangerouslySetInnerHTML={{__html:JSON.stringify({thesis:'A film publication opens into a working learning studio.',world:'Approved direction A. Charcoal, ivory, restrained acid. Barlow Condensed / DM Sans. Original photography.',story:'Observe a technique, make a study, reflect, and earn a clearly labeled demo certificate.',firstViewport:'Photographic face dominates right; closely composed promise and clear course/preview entry occupy left.',form:'User-pinned cinematic direction A; code-led implementation follows the explicit build order.',finish:'unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, DESIGN.md, and every shipping raster carrying its provenance'})}}/><LearnerProvider><a className="skip-link" href="#main">Skip to content</a><Navigation/><StorageNotice/><main id="main">{children}</main><footer className="site-footer"><div className="footer-top"><Wordmark/><p>Learn to see differently.</p><div><Link href="/courses/">Courses</Link><Link href="/help/">Help</Link><Link href="/contact/">Contact</Link><Link href="/demo/">Explore the demo</Link></div></div><div className="footer-bottom"><span>© 2026 FRAME ACADEMY · A fictional portfolio project.</span><span>Browser-only learning. No payment taken.</span><Link href="/privacy/">Privacy & credits</Link></div></footer></LearnerProvider></body></html>;}
