import Link from 'next/link';
import {courses,instructors} from '@/content/catalog';
import {CourseCard,Icon} from '@/components/ui';
import {PreviewLink} from '@/components/course-actions';
export default function Home(){return <>
  <section className="home-hero"><img className="hero-photo" src="/images/hero.webp" width="1536" height="1024" alt="A single warm light traces the profile of a woman in a dark studio." fetchPriority="high"/><div className="hero-shade"/><div className="hero-content wrap"><h1>LEARN TO SEE<br/><span>DIFFERENTLY.</span></h1><p className="hero-descriptor">Photography, film, and visual storytelling.</p><p className="hero-copy">Train your eye. Find your voice.<br/>Make something worth looking at.</p><div className="hero-actions"><Link className="button primary" href="/courses/">Browse courses<Icon name="arrow"/></Link><PreviewLink course={courses[0]}/></div></div><div className="hero-caption"><span>STUDY IN LIGHT</span><span>One source. A different perspective.</span></div><div className="hero-bottom wrap"><span>Learn by looking. Grow by making.</span><Link href="/courses/light-and-shadow/">Inside the studio: Light & Shadow<Icon name="arrow" size={18}/></Link></div></section>
  <section className="wrap section course-discovery"><div className="section-heading"><div><h2>A sharper way to see.</h2><p>Short courses. Specific techniques. Work you can make today.</p></div><Link className="text-link" href="/courses/">Explore all 6 courses<Icon name="arrow"/></Link></div><div className="course-grid home-course-grid">{courses.slice(0,3).map((c,i)=><CourseCard course={c} key={c.id} featured={i===0}/>)}</div></section>
  <section className="technique-section"><div className="technique-image"><img src="/images/light-shadow.webp" width="1200" height="800" alt={courses[0].imageAlt} loading="lazy"/><span className="study-caption">THE STUDY / A single light, a simple form</span></div><div className="technique-copy"><h2>THE LIGHT IS<br/>HALF THE STORY.<br/><span>THE SHADOW<br/>IS THE REST.</span></h2><p>Notice how the bright edge gives way to darkness. That transition tells you about shape, texture, and where the light lives.</p><p>In your first study, move one light. Make three frames. See what changes.</p><Link className="button primary" href="/learn/light-and-shadow/watch-the-technique/"><Icon name="play"/>Watch the 60-second lesson</Link><span className="small-text">Light & Shadow · Free lesson preview</span></div></section>
  <section className="wrap section pathway"><div className="section-heading"><h2>From first frame<br/>to final cut.</h2><p>Start with what catches your eye.<br/>Build a sequence. Give it a point of view.</p></div>{courses.slice(3).map((c,i)=><Link className="pathway-row" href={`/courses/${c.slug}/`} key={c.id}><span className="sequence-number">0{i+1}</span><img src={c.image} width="240" height="160" alt="" loading="lazy"/><div><span className="small-text">{c.subject} · {c.level}</span><h3>{c.title}</h3></div><p>{c.outcome}</p><Icon name="arrow" size={26}/></Link>)}</section>
  <section className="instructor-section wrap section"><div className="section-heading"><div><h2>Different eyes.<br/>A shared love of the craft.</h2><p>Three fictional teaching voices. One practical approach: make, compare, refine.</p></div><Link className="text-link" href="/instructors/">Meet your guides<Icon name="arrow"/></Link></div><div className="instructor-grid">{instructors.map(i=><Link className="instructor-card" href={`/instructors/${i.slug}/`} key={i.id}><img src={i.image} alt={`${i.name}, fictional instructor`} width="600" height="600" loading="lazy"/><div><h3>{i.name}</h3><span>{i.role}</span><p>“{i.approach}”</p></div><Icon name="arrow"/></Link>)}</div></section>
  <section className="start-section wrap"><h2>YOUR NEXT FRAME<br/><span>STARTS HERE.</span></h2><div><p>You don’t need a bigger kit.<br/>Just a little curiosity and a place to begin.</p><Link href="/courses/" className="button primary">Find your first course<Icon name="arrow"/></Link><Link href="/demo/" className="text-link small-text">Take a tour of the learning demo</Link></div></section>
  </>;}
