export type Subject = 'Photography' | 'Filmmaking' | 'Post-production';
export type LessonKind = 'video' | 'reading' | 'practice';
export type Chapter = { time: number; title: string; text: string; cue: string };
export type Question = { prompt: string; options: string[]; correct: number; explanation: string };
export type Instructor = { id: string; slug: string; name: string; role: string; image: string; approach: string; bio: string };
export type Lesson = { id: string; slug: string; title: string; kind: LessonKind };
export type Course = {
  id: string; slug: string; title: string; subject: Subject; level: 'Beginner' | 'Intermediate'; price: number; currency: 'USD';
  outcome: string; intro: string; instructorId: string; image: string; imageAlt: string; color: string;
  outcomes: string[]; equipment: string[]; prerequisite: string; lessons: Lesson[];
  reading: { heading: string; text: string }[]; assignment: string; checklist: string[]; reflection: string;
  chapters: Chapter[]; quiz: Question[]; videoSeconds: number;
};
export const instructors: Instructor[] = [
  {id:'mara',slug:'mara-ellis',name:'Mara Ellis',role:'Light & portraiture',image:'/images/mara.webp',approach:'Move the light. Watch what changes.',bio:'Mara is a fictional teaching persona built around patient observation. Her lessons use a single source, a familiar object and small, repeatable changes. She asks you to describe a shadow before reaching for another piece of equipment.'},
  {id:'elias',slug:'elias-noor',name:'Elias Noor',role:'Film & visual narrative',image:'/images/elias.webp',approach:'Give every frame a reason to be there.',bio:'Elias is a fictional teaching persona for storytelling with simple means. His approach begins with an action you can film in one room, then builds a sequence around what the viewer needs to understand. The exercise is small enough to finish and precise enough to learn from.'},
  {id:'june',slug:'june-park',name:'June Park',role:'Color & the edit',image:'/images/june.webp',approach:'Make a choice. Then make it consistent.',bio:'June is a fictional teaching persona for thoughtful post-production. She treats color and editing as decisions about attention. Her lessons favor comparisons, controlled adjustments and watching a sequence again with a specific question in mind.'},
];
function lessons(id: string, titles: string[]): Lesson[] {return ['video','reading','practice'].map((kind,i)=>({id:`${id}-${kind}`,slug:['watch-the-technique','read-the-frame','make-your-study'][i],title:titles[i],kind:kind as LessonKind}));}
export const courses: Course[] = [
  {
    id:'light-shadow',slug:'light-and-shadow',title:'Light & Shadow',subject:'Photography',level:'Beginner',price:49,currency:'USD',instructorId:'mara',
    outcome:'Use a single light source to shape a portrait or still life.',intro:'One light. A thousand ways to see. Learn to read the edge of a shadow, place your subject, and make a simple scene feel intentional.',image:'/images/light-shadow.webp',imageAlt:'A plaster sphere and folded linen shaped by a single warm directional light.',color:'#D0AB80',
    outcomes:['Recognize the direction and softness of a shadow.','Make three distinct studies with one light.','Choose fill or negative fill to control contrast.'],equipment:['A phone or camera with exposure lock','One window or cool-running LED light','A pale object, white card and dark cloth'],prerequisite:'No studio experience needed. Know how to take a photo and lock exposure on your camera or phone.',
    lessons:lessons('light-shadow',['One light, three decisions','Reading the edge of a shadow','Make a three-frame light study']),videoSeconds:60,
    reading:[
      {heading:'Start with the shadow',text:'Place a pale object on a table beside a window. Before taking a photograph, look at the shadow it casts. Its direction points away from the light. Its edge tells you something about the apparent size of the source: a broad nearby source usually produces a gradual transition, while a small source produces a crisper boundary. In the sphere study, the right side turns away from the source and becomes darker. That transition makes a flat photograph describe a round object. You are learning to recognize shape, not simply to make an image brighter.'},
      {heading:'Change one thing',text:'Keep the camera and object still. Photograph the object with the light near the camera axis, then to one side, then slightly behind it. If you use a window, move around the table while preserving the object-to-window distance. Front light reduces visible shading. Side light describes texture and volume. Light from behind can emphasize an edge while leaving the face dark. Lock your exposure so the camera does not automatically cancel your experiment. Compare the three photographs together. Ask which one makes the object easiest to understand and which one feels most mysterious; neither answer is automatically better.'},
      {heading:'Separate softness from brightness',text:'Soft light is not another name for dim light. Softness describes the shadow transition. Brightness describes how much light reaches the subject and how the camera records it. A large diffusing surface close to the subject can be both soft and bright. If you move a small lamp farther away, it becomes apparently smaller and usually dimmer; compensating the exposure will not soften its shadow. Use a cool-running LED and a purpose-made diffuser if available. Do not place cloth or paper against a hot lamp. Window light without direct sun is a useful starting point that needs no improvised fixture.'},
      {heading:'Choose how much darkness to keep',text:'Hold white card on the shadow side, outside the frame. It reflects some light back, revealing detail without adding another powered source. Move it away to reduce this fill. A dark cloth or black card can instead absorb stray light and deepen the shadow. In the example, the folds of the linen remain visible while the sphere keeps a clear dark side. Try to preserve that distinction. Finally, choose one frame and write a sentence connecting a physical decision to its visual effect: “I moved the card farther away so the shadow side would stay quiet.” A repeatable decision is more useful than a vague description of mood.'},
    ],assignment:'Make three photographs of the same still life: front light, side light, and side light with white-card fill. Keep the camera position and exposure consistent wherever possible. Your photographs stay on your device; submit a short written observation here.',checklist:['I made all three lighting studies.','I compared the shadow direction and edge.','I chose one frame and can explain its lighting.'],reflection:'Which position described the shape best, and what changed when you added fill?',
    chapters:[
      {time:0,title:'One light, three decisions',text:'Watch the sphere, not the lamp. Direction, apparent size and reflected light each change how a simple shape reads.',cue:'Observe the light study'},
      {time:10,title:'Find the direction',text:'The bright left face and shadow stretching right tell us the light arrives from the upper left. Read the shadow before moving anything.',cue:'Light → subject → shadow'},
      {time:20,title:'Compare the edge',text:'A narrow transition feels crisp. A broad transition feels soft. Softness depends on the apparent size of the source from the subject.',cue:'Small source / crisp edge • large source / soft edge'},
      {time:30,title:'Move to the side',text:'Front light flattens visible shading. Side light reveals the sphere’s volume and the texture in the linen. Keep exposure locked while comparing.',cue:'Front light → side light'},
      {time:40,title:'Add a little fill',text:'A white card on the shadow side reflects light back. Bring it closer to reveal more detail; move it away to keep a deeper shadow.',cue:'White card lifts the shadow'},
      {time:50,title:'Make your own study',text:'Photograph front light, side light and side light with fill. Choose one image. Describe the decision that made the shape read clearly.',cue:'Make 3 frames. Compare. Choose.'},
    ],quiz:[
      {prompt:'A cast shadow stretches to the right. Where is the main light most likely?',options:['To the left of the subject','Inside the camera','Directly below the table','Behind the shadow on the right'],correct:0,explanation:'Cast shadows extend away from the source; a rightward shadow suggests light from the left.'},
      {prompt:'What primarily makes a light source softer at the subject?',options:['A higher ISO','A larger apparent source size','A darker background','A warmer white balance'],correct:1,explanation:'A larger apparent source illuminates from more angles, broadening the shadow transition.'},
      {prompt:'Why lock exposure during a lighting comparison?',options:['To increase saturation','To remove every shadow','To stop automatic compensation from hiding changes','To keep all objects in focus'],correct:2,explanation:'Automatic exposure may brighten the darker setup and conceal the effect you are trying to compare.'},
      {prompt:'What does white card on the shadow side do?',options:['Changes lens focal length','Adds a hard cast shadow','Blocks all ambient light','Reflects existing light into the shadow'],correct:3,explanation:'White card acts as fill by reflecting light that is already present.'},
      {prompt:'Which observation is the most useful for repeating a result?',options:['It looks expensive','Moving the card away kept the shadow side darker','It feels professional','The camera did something interesting'],correct:1,explanation:'A specific physical change linked to a visible effect can be repeated and refined.'},
    ],
  },
  {
    id:'composition-motion',slug:'composition-in-motion',title:'Composition in Motion',subject:'Filmmaking',level:'Beginner',price:59,currency:'USD',instructorId:'elias',image:'/images/composition-motion.webp',imageAlt:'A cyclist crosses a concrete underpass with deliberate negative space and motion blur.',color:'#A8B1A2',outcome:'Frame a short visual sequence with clear subject emphasis.',intro:'Make the eye move with the story. Use space, direction and a purposeful change of scale to guide attention across three frames.',outcomes:['Separate a moving subject from its background.','Maintain a clear screen direction across cuts.','Use shot size to reveal useful new information.'],equipment:['A phone or camera','A safe place to film a simple action','A basic editor or three still frames'],prerequisite:'No filmmaking experience needed. You should be able to record and review a short clip.',lessons:lessons('composition-motion',['Give movement somewhere to go','Framing a clear visual path','Build a sequence around one action']),videoSeconds:60,
    reading:[
      {heading:'Decide what matters in the frame',text:'A composition is an arrangement of attention. Start with one action: a person crosses a room, a hand reaches for a cup, or a cyclist passes through a safe filming location. Decide what the viewer should notice first. In the underpass study, the cyclist separates from the pale wall and the surrounding space makes the direction of travel easy to read. The subject does not need to fill the frame to matter. Contrast, placement, movement and empty space can each carry emphasis. Before recording, scan the edges for bright objects or lines that might compete with the action.'},
      {heading:'Leave space with a purpose',text:'A moving subject often feels comfortable with space ahead of it. This is sometimes called lead room. Place the subject nearer the opposite side of the frame and observe how the image suggests a destination. Then deliberately leave less room. That version may feel constrained or anticipatory. Neither arrangement is a law. The useful question is whether the space supports the scene you intend. A thirds grid can help you test placements, but it cannot decide the meaning of your shot. Use it as a comparison tool, then turn it off and look at the whole picture.'},
      {heading:'Keep direction intelligible',text:'If a subject exits the first shot toward screen right and enters the next moving right, the audience can usually connect the movement easily. Reverse that direction without explanation and they may assume the subject turned around. Imagine a line along the action and keep consecutive cameras on the same side while learning. This is a useful continuity convention, not a restriction on creativity. If a reversal serves your idea, establish it visibly: show the subject turning, use a neutral head-on shot, or give enough environmental information for the viewer to understand the change. Clarity comes before clever cutting.'},
      {heading:'Change scale to add information',text:'Try a wide shot to locate the action, a medium shot to show the action clearly, and a close detail to reveal its consequence. Do not change scale only to make the sequence busier. Each frame should answer a new question. A wide view might show a person approaching a desk; the medium shows them sitting; the detail reveals the note they find. Keep the position of important objects consistent. Watch the sequence without sound and describe what happened in one sentence. If you cannot, remove a distracting shot or make the missing relationship visible. Your three-frame assignment tests attention and continuity, not equipment quality.'},
    ],assignment:'Record or photograph one simple action in wide, medium and close views. Keep its screen direction consistent. Assemble the views in order or compare them side by side. Do not film in traffic or direct a person into an unsafe position.',checklist:['I identified a single subject and action.','I made three views with purposeful scale changes.','I checked screen direction and distracting edges.'],reflection:'What new information does each frame add, and where does your eye go first?',chapters:[
      {time:0,title:'Give movement somewhere to go',text:'The cyclist is small but clear. A quiet background and space ahead let movement organize the frame.',cue:'Subject + direction + space'},
      {time:10,title:'Separate the subject',text:'Check contrast against the background. A busy shape behind a face or wheel can hide the action even when your subject is centered.',cue:'Look at the silhouette'},
      {time:20,title:'Use lead room',text:'Leave room in front of the moving subject. Compare a balanced position with a deliberately tight one and notice the different tension.',cue:'Space ahead suggests a destination'},
      {time:30,title:'Keep screen direction',text:'Rightward motion followed by rightward motion connects easily. An unexplained reversal can suggest the subject turned back.',cue:'Shot A → Shot B →'},
      {time:40,title:'Change scale for a reason',text:'Wide: where are we? Medium: what is happening? Detail: what matters now? Each cut should give useful information.',cue:'WIDE / MEDIUM / DETAIL'},
      {time:50,title:'Film one action',text:'Make three views. Check the edges and direction. Watch without sound and describe the action in one clear sentence.',cue:'Three views. One readable action.'},
    ],quiz:[
      {prompt:'What is lead room?',options:['Empty space ahead of a moving or looking subject','The first room used on a film set','A type of color correction','The longest shot in a sequence'],correct:0,explanation:'Lead room gives movement or a gaze space within the composition.'},
      {prompt:'Why might unexplained screen-direction reversal confuse a viewer?',options:['It always lowers resolution','It removes contrast','It may suggest the subject turned around','It makes sound quieter'],correct:2,explanation:'Viewers use motion direction to connect shots and infer movement.'},
      {prompt:'A close-up should ideally do what?',options:['Always hide the location','Reveal relevant new information','Replace every wide shot','Make a clip longer'],correct:1,explanation:'A meaningful change of scale changes what the audience can understand.'},
      {prompt:'Which helps separate a subject from a busy background?',options:['Adding more background objects','Ignoring the frame edges','Always centering it','Finding a quieter area or useful contrast'],correct:3,explanation:'Background simplicity and contrast can make the subject easier to recognize.'},
      {prompt:'What is a useful way to test visual clarity?',options:['Watch without sound and describe the action','Add a music track first','Speed everything up','Count the number of camera models'],correct:0,explanation:'Removing sound exposes whether the images communicate the action on their own.'},
    ],
  },
  {
    id:'portraits-presence',slug:'portraits-with-presence',title:'Portraits with Presence',subject:'Photography',level:'Intermediate',price:69,currency:'USD',instructorId:'mara',image:'/images/portraits-presence.webp',imageAlt:'A fictional woman with cropped hair in soft side light against a deep olive studio background.',color:'#ADB294',outcome:'Plan a portrait through light, background, and direction.',intro:'A portrait begins before the shutter. Make room for a person, build a simple setting, and give direction that can actually be followed.',outcomes:['Plan a portrait using three deliberate choices.','Give clear, respectful direction instead of vague poses.','Evaluate background, eye line and light together.'],equipment:['A phone or camera','Window light and a quiet background','A willing adult subject, or yourself'],prerequisite:'Comfort with basic exposure and focus. Light & Shadow is a useful starting point.',lessons:lessons('portraits-presence',['A person, not a pose','Three choices before the shutter','Make a deliberate portrait pair']),videoSeconds:60,
    reading:[
      {heading:'Begin with a shared intention',text:'Before positioning a person, explain what you want to explore and how the photograph will be used. Ask whether the idea feels comfortable and give them room to decline. A direction such as “quiet, direct and slightly off-center” is more useful when paired with a simple visual plan. In our fictional portrait study, a plain dark shirt and restrained background leave attention on the face. That is a choice, not a claim that every portrait should be minimal. Write three decisions before the session: what the light will describe, what the background contributes, and where the subject will look.'},
      {heading:'Build the background first',text:'Look through the camera at the empty setting. Remove distractions that have no role, especially bright patches behind the head and lines that appear to grow out of the subject. Leave enough distance from the wall to control shadows and separation. A darker background may emphasize a lit face, but it can also hide dark hair or clothing. Check those edges in the actual image, not just with your eyes in the room. Keep any practical adjustment simple. Turning the chair or moving a step sideways often changes the relationship more effectively than adding equipment.'},
      {heading:'Give one direction at a time',text:'Ask for a small physical action: “Turn your shoulders a little toward the window,” or “Look just past my left shoulder.” Pause and observe before adding another request. Avoid judging a person’s appearance when you are trying to adjust a photograph. Say “I want the light to reach this side of the face” rather than “That side looks wrong.” A rigid sequence of instructions can make expression feel strained. Invite the person to relax between photographs and check in during the process. Their comfort matters more than reproducing a reference exactly; you are collaborating with a person rather than arranging an object.'},
      {heading:'Compare relationships, not isolated details',text:'Make two frames that differ in one planned decision, such as looking toward the camera or toward the light. Keep the other conditions as consistent as possible. Compare the catchlight, the shadow transition, background separation and the feeling of the eye line together. A technically sharp eye does not rescue an unclear intention, and a dramatic shadow does not automatically create presence. Choose the frame that best matches the agreed idea and explain why in ordinary language. For this exercise, keep the photographs on your own device and save only your written reflection in the academy. You can use a self-portrait if a willing subject is unavailable.'},
    ],assignment:'Make two portraits with a willing adult subject or yourself. Establish the same light and background, then vary only the eye line or shoulder angle. Explain your choice without making judgments about the person’s appearance.',checklist:['I agreed on the idea and image use with my subject, or used a self-portrait.','I checked the background and light before directing.','I made two frames with one deliberate change.'],reflection:'Which change best supported the portrait’s intention, and how did you communicate it?',chapters:[
      {time:0,title:'A person, not a pose',text:'Begin with a shared idea and a willing subject. Light, background and direction should support that intention.',cue:'Agree on the intention'},
      {time:10,title:'Quiet the background',text:'Check bright patches and lines behind the head. Move the camera or subject until the face has a clear place in the frame.',cue:'Check the edges first'},
      {time:20,title:'Read the face in light',text:'The lit cheek and gradual shadow describe the face. Look for detail on both sides before choosing your exposure.',cue:'Light describes; shadow shapes'},
      {time:30,title:'Give one clear direction',text:'“Look just past my shoulder” is something a person can do. Make one request, pause, and observe the result.',cue:'One instruction. Then a pause.'},
      {time:40,title:'Compare the eye line',text:'A direct gaze addresses the viewer. A gaze out of frame points attention elsewhere. Choose the relationship your portrait needs.',cue:'Toward the viewer / beyond the frame'},
      {time:50,title:'Make a portrait pair',text:'Keep light and background. Change one direction. Compare the frames and explain which one matches the agreed idea.',cue:'Two portraits. One deliberate change.'},
    ],quiz:[
      {prompt:'What should happen before a portrait session?',options:['Choose a filter without discussion','Agree on the idea and intended image use','Demand a fixed expression','Hide the camera'],correct:1,explanation:'A shared intention and consent establish a respectful basis for the work.'},
      {prompt:'Which is actionable direction?',options:['Be more cinematic','Look expensive','Turn your shoulders slightly toward the window','Have more presence'],correct:2,explanation:'A specific physical request is easier to understand and evaluate than an abstract judgment.'},
      {prompt:'Why check the background before positioning the subject?',options:['To catch competing lines and bright patches','To guarantee a perfect portrait','To avoid needing focus','To remove all color'],correct:0,explanation:'Background relationships can distract from the face and are often easy to adjust early.'},
      {prompt:'What is a good comparison for this exercise?',options:['Different subjects, lights and lenses at once','Two unrelated images','Every setting changed','Same setup with one eye-line change'],correct:3,explanation:'Changing one variable makes the effect of your decision easier to understand.'},
      {prompt:'If a subject is uncomfortable with a direction, what is appropriate?',options:['Repeat it more forcefully','Pause and adapt or stop','Take the photograph secretly','Ignore the discomfort'],correct:1,explanation:'The subject’s comfort and choice take priority over matching a visual plan.'},
    ],
  },
  {
    id:'short-film',slug:'the-art-of-the-short-film',title:'The Art of the Short Film',subject:'Filmmaking',level:'Beginner',price:79,currency:'USD',instructorId:'elias',image:'/images/short-film.webp',imageAlt:'A person reads a letter in an amber-lit diner viewed through a rain-streaked window.',color:'#D6AD75',outcome:'Turn a small idea into a coherent three-shot sequence.',intro:'Start small. A place, a decision, a consequence. Tell a complete visual beat in three purposeful shots.',outcomes:['Write a filmable idea with a visible change.','Plan an establishing, action and consequence shot.','Check continuity and remove unnecessary information.'],equipment:['A phone or camera','One accessible location and a simple prop','Any editor that can trim and join clips'],prerequisite:'No screenwriting background required. Choose an action you can safely stage in a familiar location.',lessons:lessons('short-film',['A story in three shots','From an idea to a visible change','Film a small turning point']),videoSeconds:60,
    reading:[
      {heading:'Find a change you can show',text:'A short sequence does not need a large plot. It needs a visible difference between the beginning and the end. Someone finds a note, hesitates, and puts it away. A cup is prepared and left untouched. A chair moves toward an open window. Write the idea in one sentence using actions that a camera can record. “A person feels nostalgic” names an internal state but does not tell you what to film. “A person unfolds an old note, then carefully refolds it” gives you something observable. The meaning may remain open while the action stays clear.'},
      {heading:'Give each shot a job',text:'Begin with a view that establishes enough place for the action to make sense. Our fictional diner image places one reader in a quiet booth, framed by the window. A second, closer view could show the letter being opened. A final detail might show it returned to an envelope or set aside. These are three distinct jobs: locate, reveal and register a consequence. The order can change if you have a reason, but avoid three beautiful shots that all say the same thing. Sketch rough rectangles and label the information each contains before recording anything.'},
      {heading:'Plan for an honest cut',text:'Keep track of the prop’s position, the hand holding it, and the direction the person faces. Record a little stillness before and after the action so you have room to trim. If you repeat the action for a closer view, begin from the same recognizable position. A cut on movement can connect views, but it cannot fix a prop that jumps inexplicably between hands. For a first exercise, use one location and one simple action. Keep the camera steady enough to read the event. Elaborate movement is optional; understandable relationships are not.'},
      {heading:'Watch what the ending changes',text:'Assemble the three shots and watch without music or explanatory titles. Ask a viewer to describe only what they saw happen, without prompting them toward your intended emotion. If they miss the crucial change, adjust the shot that should reveal it or hold it a little longer. If the action is clear but the feeling differs from yours, examine context, timing and the final image. Ambiguity can be useful when it is deliberate. Your assignment is complete when the sequence has a readable action and you can explain how the last shot changes the first. A modest finished study is more informative than an ambitious plan you never film.'},
    ],assignment:'Write a one-sentence idea, sketch three shots, and record a 10–30 second sequence around a simple prop. Use the last shot to show a consequence. Keep the footage on your device and submit the three-shot logic as a reflection.',checklist:['I wrote an idea with a visible change.','I made establishing, action and consequence shots.','I checked the sequence without music or explanatory titles.'],reflection:'Describe the three shots. What does the final image change about the opening?',chapters:[
      {time:0,title:'A story in three shots',text:'A place. An action. A consequence. A small visible change can carry a complete visual beat.',cue:'PLACE → ACTION → CONSEQUENCE'},
      {time:10,title:'Write what can be filmed',text:'“Feels uncertain” is internal. “Opens a letter, pauses, puts it away” gives the camera observable actions.',cue:'Use visible verbs'},
      {time:20,title:'Establish the place',text:'The diner window locates our reader. A wide view gives the closer action a context.',cue:'Shot 1: where are we?'},
      {time:30,title:'Reveal the action',text:'Move closer to the letter. Keep hand, prop and screen direction consistent when repeating the movement.',cue:'Shot 2: what changes?'},
      {time:40,title:'Show a consequence',text:'A letter kept or left behind means something different. Let the final image register the decision.',cue:'Shot 3: what remains?'},
      {time:50,title:'Make a small turning point',text:'Sketch three views, film them, and watch without music. Can another viewer describe the visible change?',cue:'One location. One prop. Three shots.'},
    ],quiz:[
      {prompt:'Which idea is most directly filmable?',options:['A person has a complex personality','Life feels different','A person opens a note and tears it in half','A mood exists'],correct:2,explanation:'Visible actions provide concrete material for shots and a change the audience can see.'},
      {prompt:'What is the main job of an establishing shot?',options:['Provide enough spatial context','Always show a landscape','Display all equipment','Replace the ending'],correct:0,explanation:'It locates the action so closer views have a readable context.'},
      {prompt:'Why record stillness around the action?',options:['To fill storage','To avoid editing','To make every shot longer','To leave room for trimming and cuts'],correct:3,explanation:'A little extra time before and after the event gives you practical editing options.'},
      {prompt:'Which continuity detail should you watch?',options:['The price of the camera','The hand holding the prop','The file name length','The brand of the tripod'],correct:1,explanation:'A prop switching hands between matching actions can create an unintended jump.'},
      {prompt:'What should the final shot contribute?',options:['Only a logo','An unrelated beautiful image','A readable consequence or changed understanding','The same information as the first shot'],correct:2,explanation:'A consequence allows the sequence to feel like a visual beat with an ending.'},
    ],
  },
  {
    id:'color-mood',slug:'color-and-mood',title:'Color & Mood',subject:'Post-production',level:'Intermediate',price:59,currency:'USD',instructorId:'june',image:'/images/color-mood.webp',imageAlt:'A cobalt glass vessel, orange persimmon and rust fabric on a dark navy surface.',color:'#9CACC9',outcome:'Explain and apply a simple color treatment consistently.',intro:'Color is a decision about attention. Build a restrained palette, protect believable neutrals, and make a small set of images belong together.',outcomes:['Separate basic correction from a creative treatment.','Identify dominant, supporting and accent colors.','Match a treatment across three images without hiding differences.'],equipment:['Three related photographs or clips','An editor with exposure, white balance and saturation','A display in reasonably consistent room light'],prerequisite:'Comfort opening and adjusting images in an editor. No specialist color-grading software required.',lessons:lessons('color-mood',['Build a color relationship','Correct first, then create a mood','Make a consistent three-image set']),videoSeconds:60,
    reading:[
      {heading:'Give the palette a hierarchy',text:'Look at the color study before opening any controls. The deep blue field occupies most of the image. The rust cloth supports the warm region, while the smaller orange fruit draws attention through contrast. These roles are more useful than a long list of color names. A dominant color establishes the environment, a supporting color gives it variety, and an accent can point to a subject. The same hue can serve different roles when its area or brightness changes. Describe which color leads in your own image and whether that relationship helps the viewer find what matters.'},
      {heading:'Correct the starting point',text:'Basic correction gives related images a workable common starting point. Check exposure, white balance and obvious differences in contrast before adding a creative treatment. If one photograph is much warmer because of mixed lighting, applying the same preset to all three will preserve that mismatch. Use a neutral object when one is available, but do not assume every white-looking surface was neutral under the actual light. Move controls in small steps and compare with the original. The goal is not to erase the lighting conditions; it is to distinguish an intentional difference from an accidental one.'},
      {heading:'Treat less than everything',text:'Choose a short rule for your treatment: “Keep shadows slightly cool, preserve warm highlights, and lower overall saturation a little.” That is specific enough to test. Avoid pushing all colors toward the same extreme simply because the result looks striking on one frame. Skin, familiar objects and neutral materials help viewers judge whether a color choice feels believable. Watch for clipped channels, blocked shadows and color noise as you work. If your editor has scopes, use them alongside your eyes. If it does not, compare several brightness levels and do not rely on a tiny preview.'},
      {heading:'Match relationships across the set',text:'Apply your chosen rule to three related images, then view them together at the same size against a neutral background. Identical slider values are not the same as a visual match: different starting exposures and lighting may need different corrections. Compare the important relationships instead. Does the accent remain useful? Are similar neutrals reasonably consistent? Does one frame suddenly feel much denser or more saturated? Adjust that frame in context and save a before-and-after pair. Write down the treatment rule and the one correction that varied across the set. Color creates a reading of the scene; it does not carry a universal emotional meaning independent of subject, culture and context.'},
    ],assignment:'Choose three related images. Correct obvious exposure and white-balance mismatches, then apply a simple treatment with one dominant color relationship. Compare the set and write a repeatable rule for the look.',checklist:['I corrected the three starting images.','I applied one treatment rule across the set.','I compared neutrals, important colors and shadow detail.'],reflection:'What is your treatment rule, and which image needed a different correction to fit the set?',chapters:[
      {time:0,title:'Build a color relationship',text:'Blue leads the field. Rust supports the warm region. A small orange accent gives the eye somewhere to land.',cue:'DOMINANT / SUPPORT / ACCENT'},
      {time:10,title:'Describe before adjusting',text:'Name the important color roles and their relative area. Decide whether the accent points to your subject.',cue:'Area changes the role of a color'},
      {time:20,title:'Correct the starting point',text:'Compare exposure and white balance first. One preset cannot automatically repair three different starting conditions.',cue:'CORRECTION → TREATMENT'},
      {time:30,title:'Write a simple rule',text:'Try cool shadows, restrained saturation and preserved warm highlights. Small linked decisions are easier to repeat than random sliders.',cue:'A rule you can explain'},
      {time:40,title:'Compare the set',text:'Match the visual relationships, not just the numbers. Check familiar colors and keep useful shadow detail.',cue:'Same intention ≠ identical settings'},
      {time:50,title:'Make three images belong',text:'Save a before-and-after pair. Write the treatment rule and explain which correction differed across your three images.',cue:'Correct. Treat. Compare.'},
    ],quiz:[
      {prompt:'What should generally precede a creative treatment?',options:['Exporting the final','Basic exposure and white-balance correction','Maximum saturation','A heavy vignette'],correct:1,explanation:'A coherent starting point makes the creative treatment easier to control across images.'},
      {prompt:'Why can identical settings still produce a mismatch?',options:['Images may start with different lighting and exposure','Settings are always random','Color never changes','All editors ignore settings'],correct:0,explanation:'The same adjustment acts on different starting images, so visual matching may need different corrections.'},
      {prompt:'What makes an accent color useful?',options:['It must cover every pixel','It must always be red','It can direct attention through contrast and limited area','It removes the subject'],correct:2,explanation:'An accent is a relational role; contrast and area can help it draw attention.'},
      {prompt:'Which is a repeatable treatment rule?',options:['Make it amazing','Do something cinematic','Use many random filters','Cool shadows slightly while preserving warm highlights'],correct:3,explanation:'A specific rule links controllable adjustments to an intended relationship.'},
      {prompt:'How should you evaluate a three-image treatment?',options:['Only examine one thumbnail','Compare the set at equal size with consistent viewing conditions','Always choose identical slider values','Ignore neutral objects'],correct:1,explanation:'Consistent side-by-side viewing exposes differences in density, neutrals and saturation.'},
    ],
  },
  {
    id:'edit-story',slug:'edit-for-the-story',title:'Edit for the Story',subject:'Post-production',level:'Intermediate',price:69,currency:'USD',instructorId:'june',image:'/images/edit-story.webp',imageAlt:'A filmmaker’s tabletop with contact prints showing a coffee-making sequence and an editing notebook.',color:'#C4B6A2',outcome:'Assemble a short sequence with intentional rhythm and continuity.',intro:'Find the cut that makes the thought clear. Shape a small sequence through order, duration and the information you choose to leave out.',outcomes:['Organize selects by their role in a sequence.','Trim a cut around an action while checking continuity.','Compare two rhythms and choose the one that supports the story.'],equipment:['Three or more clips of a simple action','An editor with trim and reorder controls','Headphones if your clips include useful sound'],prerequisite:'Know how to import, trim and arrange clips. Your own three-shot film can supply the material.',lessons:lessons('edit-story',['Every cut changes the thought','Order, duration and continuity','Build two versions of an edit']),videoSeconds:60,
    reading:[
      {heading:'Select for information',text:'Before placing clips on a timeline, write down what each shot contributes. In the coffee contact-sheet study, a wide view can establish the work surface, a closer view can show the preparation, and a detail can reveal the pour. A technically attractive clip may still be redundant. Choose a small set that lets the viewer connect cause and effect. Keep alternatives nearby without putting every possibility into the sequence. This first pass is about the meaning of the material, not the speed of your editing software. Name clips by their action if the original file names do not help you recognize them.'},
      {heading:'Build a readable order',text:'Arrange the essential actions in an order that makes sense, then watch without transitions or music. The viewer should understand what changes from one shot to the next. Chronological order is a useful starting point, but you may withhold a detail to create a question and reveal it later. That choice should be intentional. If a cup appears full before the pour without an explanation, the sequence may suggest a mistake rather than a new idea. Check the state of props and the direction of movement alongside the overall logic. Clean relationships are more useful than elaborate transition effects.'},
      {heading:'Trim around a reason',text:'At each cut, ask when the viewer has enough information and what the next shot should add. A cut during movement can join two views smoothly when the action matches. Look for the phase of the gesture, not only the position of the hand: a reach should continue as a reach. Small overlaps can sometimes feel better than an exact mathematical match because the viewer needs time to recognize the new angle. Try the cut several frames earlier and later. Judge it while playing the sequence, not only while stepping through still frames. Repetition can make a rough cut feel familiar, so take a short break before deciding.'},
      {heading:'Compare rhythm with intention',text:'Duplicate your sequence and make two versions from the same selected clips. In one, hold long enough to observe the preparation. In the other, shorten the pauses while preserving readable actions. Watch both at normal speed. Faster is not automatically more engaging, and slower is not automatically more thoughtful. Choose based on the experience you intended and the clarity of the action. If the ending is important, give the viewer enough time to register it. Save both versions on your device and record which cut changed the feeling most. The useful result is an explanation tied to a specific timing choice, not a universal formula for shot length.'},
    ],assignment:'Create two short edits from the same clips: an observational version and a tighter version. Preserve understandable actions in both. Compare them at normal playback speed and choose one based on your intended experience.',checklist:['I selected clips by the information they contribute.','I checked action, prop and screen-direction continuity.','I compared two rhythms at normal speed.'],reflection:'Which timing choice changed the experience most, and why did you choose your final version?',chapters:[
      {time:0,title:'Every cut changes the thought',text:'These coffee-making views carry different information. Select for the job of each shot before polishing the timeline.',cue:'PLACE / PREPARATION / POUR'},
      {time:10,title:'Choose useful information',text:'A beautiful shot can still repeat what we know. Keep the views that establish, advance or resolve the action.',cue:'What does this shot add?'},
      {time:20,title:'Build the order',text:'Check cause and effect. An empty cup, a pour and a filled cup form a readable change when their order is intentional.',cue:'EMPTY → POUR → FULL'},
      {time:30,title:'Cut through an action',text:'Match the phase of a gesture across views. Test the cut a few frames earlier and later while playing at normal speed.',cue:'Reach → continue the reach'},
      {time:40,title:'Compare two rhythms',text:'Hold to let us observe. Trim to remove hesitation. Faster is only better when the action and intention remain clear.',cue:'OBSERVATIONAL / TIGHTER'},
      {time:50,title:'Choose your edit',text:'Keep the same clips. Make two versions. Explain one timing decision that changed how the sequence feels.',cue:'Same material. Different experience.'},
    ],quiz:[
      {prompt:'What is a useful first criterion for selecting a shot?',options:['Its file size','The information it contributes','Whether it is the longest','Whether it has a transition'],correct:1,explanation:'A shot earns its place by supporting the sequence’s meaning or action.'},
      {prompt:'When matching an action across a cut, check what?',options:['Only the file names','The number of tracks','The phase and direction of the gesture','The editor’s theme'],correct:2,explanation:'Matching the phase and direction helps a movement continue naturally across views.'},
      {prompt:'Why compare two versions made from the same clips?',options:['To isolate the effect of timing and order','To double the resolution','To avoid choosing','To make the computer faster'],correct:0,explanation:'Keeping the material constant helps reveal how editorial choices change the experience.'},
      {prompt:'Is a faster edit always more engaging?',options:['Yes, without exception','Only with expensive software','Yes, if it has more cuts','No; clarity and intended experience matter'],correct:3,explanation:'Rhythm should serve the action and intention; speed has no universal advantage.'},
      {prompt:'How should you judge a small timing change?',options:['Only from a still thumbnail','Play the sequence at normal speed in context','Only from the timeline width','Ignore surrounding shots'],correct:1,explanation:'A cut is a relationship in time, so playback with surrounding shots is essential.'},
    ],
  },
];
export const getCourse = (slugOrId: string) => courses.find(c=>c.slug===slugOrId || c.id===slugOrId);
export const getInstructor = (id: string) => instructors.find(i=>i.id===id || i.slug===id);
export const lessonUrl = (course: Course, lesson: Lesson | string) => `/learn/${course.slug}/${typeof lesson==='string'?lesson:lesson.slug}/`;
export const readingMinutes = (c: Course) => Math.ceil(c.reading.reduce((n,p)=>n+p.text.split(/\s+/).length,0)/200);
export const formatTime = (n: number) => `${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
export const money = (c: Pick<Course,'price'|'currency'>) => new Intl.NumberFormat('en-US',{style:'currency',currency:c.currency,maximumFractionDigits:0}).format(c.price);
