import Link from 'next/link';
import type {ReactNode} from 'react';
import {getInstructor,money,readingMinutes,type Course} from '@/content/catalog';
import {SaveButton} from './course-actions';
export function Icon({name,size=20}:{name:'arrow'|'play'|'save'|'check'|'close'|'menu'|'search'|'download'|'note'|'book'|'chevron'|'share'|'plus'|'clock';size?:number}) {
  const paths:Record<typeof name,ReactNode>={arrow:<path d="M4 12h16m-6-6 6 6-6 6"/>,play:<path d="m9 5 11 7-11 7Z"/>,save:<path d="M6 3h12v18l-6-4-6 4Z"/>,check:<path d="m5 12 4 4L19 6"/>,close:<path d="m6 6 12 12M6 18 18 6"/>,menu:<path d="M4 6h16M4 12h16M4 18h16"/>,search:<><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></>,download:<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>,note:<><path d="M5 3h14v18H5Z"/><path d="M9 8h6m-6 4h6m-6 4h4"/></>,book:<path d="M12 5v16M12 5C9 3 5 3 2 4v15c4-1 7-1 10 2 3-3 6-3 10-2V4c-3-1-7-1-10 1Z"/>,chevron:<path d="m9 5 7 7-7 7"/>,share:<><circle cx="18" cy="5" r="3"/><circle cx="5" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8 10 7-4M8 14l7 4"/></>,plus:<path d="M12 4v16M4 12h16"/>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>};
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
export function Mark(){return <svg className="mark" width="34" height="34" viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M3 15V3h12m10 0h12v12m0 10v12H25m-10 0H3V25" stroke="currentColor" strokeWidth="2.5"/><path d="M15 15h10v10H15z" fill="currentColor"/></svg>;}
export function Wordmark(){return <Link className="wordmark" href="/" aria-label="Frame Academy home"><Mark/><span>FRAME<span className="wordmark-academy">ACADEMY</span></span></Link>;}
export function CourseCard({course:c,featured=false}:{course:Course;featured?:boolean}){const teacher=getInstructor(c.instructorId)!;return <article className={`course-card ${featured?'featured-card':''}`}><div className="course-image"><Link href={`/courses/${c.slug}/`} tabIndex={-1} aria-hidden="true"><img src={c.image} alt="" width="1200" height="800" loading="lazy"/></Link><span className="image-label">{c.subject}</span><SaveButton courseId={c.id} compact/></div><div className="card-meta"><span>{c.level}</span><span>3 lessons · {c.videoSeconds}s video</span></div><Link className="course-title-link" href={`/courses/${c.slug}/`}><h3>{c.title}</h3><Icon name="arrow"/></Link><p>{c.outcome}</p><div className="card-bottom"><span>{teacher.name}</span><span>{money(c)} <small>demo</small></span></div></article>;}
export function CourseFacts({course:c}:{course:Course}){return <div className="facts"><span>{c.level}</span><span>3 lessons + quiz</span><span>{c.videoSeconds}s video</span><span>~{readingMinutes(c)} min reading</span></div>;}
export function EmptyState({title,text,href='/courses/',action='Explore courses'}:{title:string;text:string;href?:string;action?:string}){return <div className="empty-state"><Mark/><h2>{title}</h2><p>{text}</p><Link className="button" href={href}>{action}<Icon name="arrow"/></Link></div>;}
export function PageHeading({title,children}:{title:string;children?:ReactNode}){return <div className="page-heading"><h1>{title}</h1>{children&&<p>{children}</p>}</div>;}
export function DemoDisclosure(){return <p className="demo-disclosure">Portfolio demo. Learning data is stored in this browser. No payment is taken.</p>;}
