import {chromium,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import sharp from 'sharp';
const {courses}=await import('../src/content/catalog.ts');
const base=process.env.PREVIEW_URL||'http://127.0.0.1:4173';
const key='frame-academy:demo:v1',c=courses[0];
const browser=await chromium.launch({channel:'chrome',headless:true});
const report={browser:await browser.version(),base,checks:[],media:[],a11y:[],metrics:[],overflow:[],errors:[]};
await fs.mkdir('docs/screenshots',{recursive:true});await fs.mkdir('docs/downloads',{recursive:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,acceptDownloads:true});
await context.addInitScript(()=>{window.__frameVitals={lcp:0,cls:0};try{new PerformanceObserver(list=>{for(const entry of list.getEntries())window.__frameVitals.lcp=entry.startTime;}).observe({type:'largest-contentful-paint',buffered:true});new PerformanceObserver(list=>{for(const entry of list.getEntries())if(!entry.hadRecentInput)window.__frameVitals.cls+=entry.value;}).observe({type:'layout-shift',buffered:true});}catch{}});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
async function go(url){const response=await page.goto(base+url);assert(response?.status()<400,`${url}: ${response?.status()}`);await page.evaluate(()=>document.fonts.ready);}
async function saved(){return page.evaluate(k=>JSON.parse(localStorage.getItem(k)||'{}'),key);}
function pass(message){report.checks.push(message);console.log('PASS '+message);}
async function capture(name){await page.evaluate(async()=>{if(document.activeElement instanceof HTMLElement)document.activeElement.blur();window.scrollTo({top:0,left:0,behavior:'instant'});for(const img of document.images)img.loading='eager';await Promise.all(Array.from(document.images).map(img=>img.decode().catch(()=>{})));});await page.screenshot({path:`docs/screenshots/${name}.png`,fullPage:true});}
async function audit(name){const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();report.a11y.push({name,violations:result.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});}
async function metrics(name){report.metrics.push(await page.evaluate(name=>{const nav=performance.getEntriesByType('navigation')[0],resources=performance.getEntriesByType('resource');return {name,viewport:{width:innerWidth,height:innerHeight},lcpMs:window.__frameVitals.lcp,cls:window.__frameVitals.cls,domContentLoadedMs:nav.domContentLoadedEventEnd,resourceTransferBytes:resources.reduce((n,r)=>n+r.transferSize,0),requests:resources.length};},name));}
try{
await go('/');await expect(page.getByRole('heading',{level:1})).toContainText('LEARN TO SEE');await page.keyboard.press('Tab');assert(await page.locator('.skip-link').evaluate(el=>el===document.activeElement));pass('Keyboard skip link and public homepage');
await go('/courses/');await page.getByLabel('Subject',{exact:true}).selectOption('Photography');await page.getByLabel('Experience').selectOption('Beginner');await expect(page.locator('.course-card')).toHaveCount(1);assert(page.url().includes('subject=Photography'));await page.reload();await expect(page.locator('.course-card')).toHaveCount(1);await page.getByRole('button',{name:'Save Light & Shadow',exact:true}).click();await go('/saved/');await expect(page.getByRole('heading',{name:'Light & Shadow',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Light & Shadow',exact:true})).toBeVisible();await go('/courses/?q=zzznomatch');await expect(page.getByRole('heading',{name:'Try a different point of view.'})).toBeVisible();await go('/courses/?sort=price-asc');await expect(page.locator('.course-card').first()).toContainText('Light & Shadow');pass('Catalog filters/search/sort, URL persistence, empty results and saved courses');
await go('/courses/light-and-shadow/');await page.reload();await page.getByRole('link',{name:'Step inside the lesson'}).click();await page.waitForURL('**/learn/light-and-shadow/watch-the-technique/');await expect.poll(()=>page.locator('video').evaluate(v=>v.readyState)).toBeGreaterThanOrEqual(2);await page.locator('video').evaluate(v=>v.play());await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime)).toBeGreaterThan(1);await page.locator('video').evaluate(v=>v.pause());assert(!(await saved()).enrollments?.[c.id]);pass('Actual H.264 preview playback before enrollment');
await go('/certificate/?course=light-and-shadow');await expect(page.getByRole('heading',{name:'A little more work to make.'})).toBeVisible();await go('/enroll/?course=light-and-shadow');await page.getByLabel('Sample learner name (optional)').fill('Alex Morgan');await page.getByRole('button',{name:'Enroll in demo',exact:true}).click();await page.waitForURL('**/enrollment/confirmation/?ref=*');const receipt=page.url();await expect(page.getByRole('heading',{name:/You’re in/})).toBeVisible();const original=(await saved()).enrollments[c.id];await page.reload();await expect(page.getByText(original.ref,{exact:true})).toBeVisible();await go('/enroll/?course=light-and-shadow');await page.getByRole('button',{name:'Continue existing enrollment'}).click();await expect(page).toHaveURL(receipt);assert.equal(Object.keys((await saved()).enrollments).length,1);pass('Credential-free enrollment, persistent confirmation and duplicate receipt reuse');
await page.getByRole('link',{name:'Enter the learning studio'}).click();await expect.poll(()=>page.locator('video').evaluate(v=>v.readyState)).toBeGreaterThanOrEqual(2);await page.locator('video').evaluate(v=>{v.currentTime=22;v.volume=.4;v.muted=true;});await page.getByLabel('Playback speed',{exact:true}).selectOption('1.5');await expect.poll(()=>page.locator('video').evaluate(v=>v.playbackRate)).toBe(1.5);await page.getByRole('button',{name:'Toggle text captions'}).click();assert.equal(await page.locator('video').evaluate(v=>v.textTracks[0].mode),'showing');await page.getByLabel('What did you notice?').fill('The shadow edge tells me about apparent source size. Compare the white card at two distances.');await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.getByText('Note saved in this browser.')).toBeVisible();await page.getByRole('button',{name:'Bookmark this moment'}).click();await page.getByRole('button',{name:'Edit note',exact:true}).click();await page.getByLabel('Edit note',{exact:true}).fill('Edited observation: move the white card away to preserve a deeper shadow.');await page.getByRole('button',{name:'Save changes'}).click();await page.locator('video').evaluate(async v=>{await v.play();v.pause();});await page.reload();await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime)).toBeGreaterThan(20);await expect(page.getByText('Edited observation:',{exact:false})).toBeVisible();await page.getByRole('tab',{name:'Transcript',exact:true}).click();await page.getByRole('button',{name:'Seek to 0:40:',exact:false}).click();await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime)).toBeCloseTo(40,0);await page.getByRole('tab',{name:'Transcript',exact:true}).focus();await page.keyboard.press('ArrowLeft');await expect(page.getByRole('tab',{name:'Notes',exact:true})).toBeFocused();await page.getByRole('button',{name:'Seek bookmark at 0:22'}).click();await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime)).toBeCloseTo(22,0);await page.getByLabel('What did you notice?').fill('A second note to delete during verification.');await page.getByRole('button',{name:'Save note',exact:true}).click();page.once('dialog',d=>d.accept());await page.locator('.note-row').last().getByRole('button',{name:'Delete',exact:true}).click();assert.equal((await saved()).notes.length,1);pass('Seek, speed, mute/volume, captions, playhead restore, notes CRUD and bookmarks');
await go('/notes/');await page.getByLabel('Search your observations').fill('white card');await expect(page.locator('.note-row')).toHaveCount(1);await page.getByLabel('Course',{exact:true}).selectOption(c.id);const noteDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export these notes'}).click();await (await noteDownload).saveAs('docs/downloads/frame-academy-notes.md');assert((await fs.readFile('docs/downloads/frame-academy-notes.md','utf8')).includes('Edited observation'));await page.getByRole('link',{name:'Light & Shadow / One light, three decisions'}).click();await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime)).toBeGreaterThan(20);pass('Global note search/filter, Markdown download and timestamp navigation');
await page.getByRole('button',{name:'Mark complete',exact:true}).click();await expect(page.getByRole('button',{name:'Lesson complete',exact:true})).toBeDisabled();await page.getByRole('link',{name:'Next lesson',exact:true}).click();await page.getByRole('button',{name:'Mark complete',exact:true}).click();await page.getByRole('link',{name:'Next lesson',exact:true}).click();await page.getByRole('button',{name:'Submit practice'}).click();await expect(page.getByText('Complete every checklist item',{exact:false})).toBeVisible();for(const item of c.checklist)await page.getByLabel(item,{exact:true}).check();await page.getByLabel(c.reflection,{exact:true}).fill('The side light described the sphere clearly. Moving the card away kept a deeper shadow and made the round shape easier to read.');await page.getByRole('button',{name:'Submit practice'}).click();await expect(page.getByText('Practice complete. Your reflection is saved with this lesson.')).toBeVisible();assert.equal(Object.keys((await saved()).certificates).length,0);pass('Manual video, explicit reading and validated practice completion; certificate remains gated');
await page.getByRole('link',{name:'Go to final quiz'}).click();await page.getByRole('button',{name:'Submit answers'}).click();await expect(page.getByText('Answer all five questions before submitting.')).toBeVisible();for(let i=0;i<5;i++)await page.locator(`input[name=q${i}][value="${(c.quiz[i].correct+1)%4}"]`).check();await page.reload();for(let i=0;i<5;i++)await expect(page.locator(`input[name=q${i}][value="${(c.quiz[i].correct+1)%4}"]`)).toBeChecked();await page.getByRole('button',{name:'Submit answers'}).click();await expect(page.locator('.quiz-result')).toContainText('0/5');await expect(page.locator('.quiz-feedback')).toHaveCount(5);await page.getByRole('button',{name:'Try again',exact:true}).click();for(let i=0;i<5;i++)await page.locator(`input[name=q${i}][value="${c.quiz[i].correct}"]`).check();await page.getByRole('button',{name:'Submit answers'}).click();await expect(page.locator('.quiz-result')).toContainText('5/5');await capture('quiz-desktop');assert.equal((await saved()).quizzes[c.id].attempts.length,2);assert.equal(Object.keys((await saved()).certificates).length,1);pass('Quiz draft, required answers, failed explanations, retry and certificate award');
await page.getByRole('link',{name:'View your demo certificate'}).click();await expect(page.locator('.certificate-name')).toHaveText('Alex Morgan');const certDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download certificate PNG'}).click();await (await certDownload).saveAs('docs/downloads/demo-certificate.png');const certMeta=await sharp('docs/downloads/demo-certificate.png').metadata();assert.equal(certMeta.width,1800);assert.equal(certMeta.height,1200);await capture('certificate-desktop');await page.pdf({path:'docs/downloads/demo-certificate-print.pdf',format:'A4',landscape:true,printBackground:true,preferCSSPageSize:true});pass('Actual certificate PNG download and browser print-to-PDF');
await go('/profile/');await page.getByLabel('Display name',{exact:true}).fill('Alexandra Marie Morgan — An intentionally long sample learner name for a multiline certificate');await page.getByRole('button',{name:'Save preferences'}).click();await go('/certificate/?course=light-and-shadow');await expect(page.locator('.certificate-name')).toHaveText('Alex Morgan');pass('Profile edits preserve issued certificate snapshots');
await go('/contact/');await page.getByLabel('Your sample request').fill('A fictional request about resuming a lesson in this local demo.');await page.getByRole('button',{name:'Save request in this demo'}).click();await expect(page.getByText('Saved in this demo.',{exact:false})).toBeVisible();await go('/demo/');await expect(page.getByText('A fictional request about resuming a lesson in this local demo.')).toBeVisible();pass('Local support request and Demo viewer');
page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Load in-progress state'}).click();await go('/my-learning/');await capture('dashboard-desktop');await audit('dashboard-desktop');await go('/learn/light-and-shadow/watch-the-technique/');await expect.poll(()=>page.locator('video').evaluate(v=>v.readyState)).toBeGreaterThanOrEqual(2);await page.locator('video').evaluate(v=>{v.currentTime=20;});await capture('player-desktop');await audit('player-desktop');await metrics('player-desktop');
for(const course of courses){await go(`/learn/${course.slug}/watch-the-technique/`);await expect.poll(()=>page.locator('video').evaluate(v=>v.readyState)).toBeGreaterThanOrEqual(2);const result=await page.locator('video').evaluate(async v=>{await v.play();return {duration:v.duration,width:v.videoWidth,height:v.videoHeight,codecSupported:v.canPlayType('video/mp4; codecs="avc1.42E01E"')};});await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime)).toBeGreaterThan(.5);await page.locator('video').evaluate(v=>v.pause());report.media.push({id:course.id,...result});}pass('Six distinct MP4 files decode and advance in Chrome');
await go('/learn/light-and-shadow/watch-the-technique/');await expect.poll(()=>page.locator('video').evaluate(v=>v.readyState)).toBeGreaterThanOrEqual(2);await page.locator('video').evaluate(async v=>{v.currentTime=59.5;await v.play();});await expect.poll(async()=>!!(await saved()).progress[c.lessons[0].id]?.completedAt).toBe(true);await go('/demo/');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Load completed state'}).click();await go('/my-learning/');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Reset progress',exact:true}).click();const state=await saved();assert(state.enrollments[c.id]);assert.equal(Object.keys(state.certificates).length,0);assert.equal(Object.keys(state.quizzes).length,0);assert.equal(state.notes.length,1);pass('Real ended completion and consistent confirmed course reset');
const separate=await browser.newContext();const fresh=await separate.newPage();await fresh.goto(base+'/my-learning/');await expect(fresh.getByRole('heading',{name:'Your next frame is waiting.'})).toBeVisible();await separate.close();pass('Separate browser contexts have independent records');
const second=await context.newPage();await second.goto(base+'/saved/');await page.goto(base+'/courses/');await page.getByRole('button',{name:'Save Edit for the Story',exact:true}).click();await expect(second.getByRole('heading',{name:'Edit for the Story',exact:true})).toBeVisible();await second.close();pass('Cross-tab saved-course updates');
await page.evaluate(k=>{localStorage.setItem('frame-unrelated-qa','preserve');localStorage.setItem(k,'{bad-json');},key);await go('/demo/');await expect(page.getByRole('button',{name:'Use temporary session'})).toBeVisible();assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),'{bad-json');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Reset all demo data'}).click();assert.equal(await page.evaluate(()=>localStorage.getItem('frame-unrelated-qa')),'preserve');assert.equal(await page.evaluate(k=>localStorage.getItem(k),key),null);pass('Corrupt storage recovery and app-scoped reset');
for(const failure of ['disabled','quota']){const ctx=await browser.newContext();await ctx.addInitScript(mode=>{if(mode==='disabled')Object.defineProperty(window,'localStorage',{get(){throw new DOMException('Disabled','SecurityError');}});else Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError');};},failure);const p=await ctx.newPage();await p.goto(base+'/enroll/?course=light-and-shadow');if(failure==='quota')await p.getByRole('button',{name:'Enroll in demo',exact:true}).click();await expect(p.getByRole('button',{name:'Use temporary session'})).toBeVisible();await p.getByRole('button',{name:'Use temporary session'}).click();await p.getByRole('button',{name:'Enroll in demo',exact:true}).click();await expect(p.getByRole('heading',{name:/You’re in/})).toBeVisible();await expect(p.getByText('Temporary page session',{exact:true})).toBeVisible();await p.reload();await expect(p.getByRole('heading',{name:'This receipt isn’t in this browser.'})).toBeVisible();await ctx.close();}pass('Disabled/quota storage and explicit temporary access');
const errorContext=await browser.newContext();await errorContext.route('**/media/light-shadow.mp4',route=>route.abort());const errorPage=await errorContext.newPage();await errorPage.goto(base+'/learn/light-and-shadow/watch-the-technique/');await expect(errorPage.getByText('This video could not load.',{exact:false})).toBeVisible();await errorContext.close();pass('Media failure provides retry and transcript recovery');
await go('/demo/');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Load in-progress state'}).click();for(const width of [1440,1024,768,390,360]){await page.setViewportSize({width,height:width<600?844:1000});for(const [name,url]of [['home','/'],['course','/courses/light-and-shadow/'],['player','/learn/light-and-shadow/watch-the-technique/'],['dashboard','/my-learning/'],['catalog','/courses/']]){await go(url);const overflow=await page.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth}));report.overflow.push({name,width,...overflow});assert(overflow.scroll<=width+1,`${name} overflow at ${width}`);if(width===1440||width===390){if(name==='player')await expect.poll(()=>page.locator('video').evaluate(v=>v.readyState)).toBeGreaterThanOrEqual(2);await capture(`${name}-${width===1440?'desktop':'mobile'}`);if(name==='home'||name==='course'){await audit(`${name}-${width}`);await metrics(`${name}-${width}`);}}}if(width===390){await go('/');await page.getByRole('button',{name:'Open navigation'}).click();await expect(page.getByRole('navigation',{name:'Mobile'})).toBeVisible();await page.getByRole('navigation',{name:'Mobile'}).getByRole('link',{name:'Courses',exact:true}).click();await expect(page.getByRole('navigation',{name:'Mobile'})).toHaveCount(0);}}pass('1440/1024/768/390/360px routes, overflow checks and mobile navigation');
await page.setViewportSize({width:390,height:844});await go('/demo/');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Load completed state'}).click();await go('/certificate/?course=light-and-shadow');await capture('certificate-mobile');await go('/learn/light-and-shadow/quiz/');await capture('quiz-mobile');await audit('quiz-mobile');await page.setViewportSize({width:1440,height:1000});await go('/');await page.evaluate(()=>document.documentElement.style.fontSize='200%');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await go('/learn/light-and-shadow/read-the-frame/');await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');pass('200% homepage text sizing and reduced-motion behavior');
const missing=await page.goto(base+'/courses/not-a-course/');assert.equal(missing.status(),404);await expect(page.getByRole('heading',{name:'OUT OF FRAME.'})).toBeVisible();await go('/enrollment/confirmation/?ref=missing');await expect(page.getByRole('heading',{name:'This receipt isn’t in this browser.'})).toBeVisible();pass('Unknown slugs and missing receipt states');
await fs.writeFile('docs/browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({checks:report.checks.length,media:report.media.length,axeViolations:report.a11y.reduce((n,a)=>n+a.violations.length,0),errors:report.errors},null,2));assert.equal(report.errors.length,0,'Unexpected browser errors');
}catch(error){report.failure=error instanceof Error?error.message:String(error);await fs.writeFile('docs/browser-results.json',JSON.stringify(report,null,2));await page.screenshot({path:'docs/screenshots/test-failure.png',fullPage:true});throw error;}finally{await browser.close();}
